/**
 * API Wizard — интерактивная настройка API-ключей.
 *
 * Для каждого скилла, требующего API-ключ:
 * 1. Объясняет ЗАЧЕМ нужен ключ (простыми словами)
 * 2. Даёт прямую ссылку где его получить
 * 3. Принимает ключ от пользователя
 * 4. Сохраняет в .env файл
 *
 * Никогда не записывает ключи в .mcp.json напрямую —
 * только через ${VAR} ссылки на .env.
 */

import { writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import chalk from "chalk";
import type { Skill, EnvVar } from "../types.js";

interface CollectedKey {
  name: string;
  value: string;
}

/**
 * Запускает интерактивный мастер настройки API-ключей.
 *
 * Возвращает true если хотя бы один ключ был настроен.
 */
export async function runApiWizard(
  targetDir: string,
  skills: Skill[],
): Promise<boolean> {
  // Собираем уникальные env-переменные из всех скиллов
  const allEnvVars = collectUniqueEnvVars(skills);

  if (allEnvVars.length === 0) {
    console.log(chalk.green("  No API keys needed — all agents work out of the box!"));
    return false;
  }

  console.log("");
  console.log(chalk.bold.white("  ─── API WIZARD ───"));
  console.log(chalk.gray("  Configure API keys for your agents."));
  console.log(chalk.gray("  Press Enter to skip any key (you can add it later in .env)"));
  console.log("");

  const rl = createInterface({ input: stdin, output: stdout });
  const collected: CollectedKey[] = [];

  try {
    for (let i = 0; i < allEnvVars.length; i++) {
      const envVar = allEnvVars[i];
      const skill = findSkillForEnv(skills, envVar.name);
      const progress = chalk.gray(`[${i + 1}/${allEnvVars.length}]`);

      console.log(`  ${progress} ${chalk.bold.white(envVar.name)}`);

      if (skill) {
        console.log(chalk.gray(`    For: ${skill.command} agent (${skill.name})`));
      }

      console.log(chalk.gray(`    Why: ${envVar.description}`));
      console.log(chalk.gray(`    Get: ${chalk.underline(envVar.getUrl)}`));

      const answer = await rl.question(chalk.cyan("    Key: "));
      const trimmed = answer.trim();

      if (trimmed.length > 0) {
        collected.push({ name: envVar.name, value: trimmed });
        console.log(chalk.green("    ✓ Saved"));
      } else {
        console.log(chalk.yellow("    ⊘ Skipped (add later in .env)"));
      }

      console.log("");
    }
  } finally {
    rl.close();
  }

  // Записываем собранные ключи в .env
  if (collected.length > 0) {
    await writeEnvFile(targetDir, collected, allEnvVars);
  }

  return collected.length > 0;
}

/**
 * Собирает уникальные env-переменные из всех скиллов.
 * Дедупликация по имени (Supabase может быть и в auth, и в database).
 */
function collectUniqueEnvVars(skills: Skill[]): EnvVar[] {
  const seen = new Set<string>();
  const result: EnvVar[] = [];

  for (const skill of skills) {
    for (const envVar of skill.requiredEnvVars) {
      if (!seen.has(envVar.name)) {
        seen.add(envVar.name);
        result.push(envVar);
      }
    }
  }

  return result;
}

/** Находит скилл, которому принадлежит данная env-переменная */
function findSkillForEnv(skills: Skill[], envName: string): Skill | undefined {
  return skills.find((s) =>
    s.requiredEnvVars.some((e) => e.name === envName),
  );
}

/**
 * Записывает .env файл. Не перезаписывает существующие переменные —
 * добавляет только новые.
 */
async function writeEnvFile(
  targetDir: string,
  collected: CollectedKey[],
  allVars: EnvVar[],
): Promise<void> {
  const envPath = join(targetDir, ".env");

  // Читаем существующий .env если есть
  let existingContent = "";
  try {
    existingContent = await readFile(envPath, "utf-8");
  } catch {
    // Файл не существует — это нормально
  }

  const existingKeys = new Set(
    existingContent
      .split("\n")
      .filter((line) => line.includes("=") && !line.startsWith("#"))
      .map((line) => line.split("=")[0].trim()),
  );

  // Добавляем только новые переменные
  const lines: string[] = [];

  if (existingContent.length === 0) {
    lines.push("# SkillPilot — API Keys");
    lines.push("# Generated by skillpilot init");
    lines.push("");
  }

  for (const key of collected) {
    if (existingKeys.has(key.name)) continue;

    const envVar = allVars.find((v) => v.name === key.name);
    if (envVar) {
      lines.push(`# ${envVar.description}`);
    }
    lines.push(`${key.name}=${key.value}`);
    lines.push("");
  }

  if (lines.length > 0) {
    const newContent = existingContent + (existingContent.endsWith("\n") ? "" : "\n") + lines.join("\n");
    await writeFile(envPath, newContent, "utf-8");
  }
}
